Adding documentation (plus a few TEB parameter tweaks)
evamo0508/Autovalet pull request #2
Opened 2020-09-04 03:44 UTC by kob51

Went thru and added more formalized readme's to every package I could. Lmk if more info is needed anywhere...

I was a little confused by what was written in the `autovalet_description` package's readme, so someone please take a look at that and lmk if it needs updating

2020-09-06 05:02 UTC, SubramanianKrish commented on autovalet_description/readme.MD
I think the readme here should go sth like this:
This is the autovalet husky URDF package. We have a modified version of the husky with a LiDAR and 2 Realsense D435s on it. We call the standard husky URDF with out autovalet.urdf.xacro as an extra. Our sensor transforms are defined in the xacro file. The URDF is published to ROS by launching the autovalet_description.launch. In order to view the robot model generated by the URDF, please launch robot state publisher and the joint state publisher along with the autovalet_description.launch file.

2020-09-06 05:03 UTC, SubramanianKrish requested changes, later dismissed
Check the autovalet_description readme. Feel free to edit it out

2020-09-08 02:37 UTC, evamo0508 commented on autovalet_lane_detection/README.md
> +This package contains our lane detection pipeline. The output of the lane detection will be used projected on the costmap, so that valid goals lying within the lane can be sent to the planner.
think we should add one line: `roslaunch autovalet_lane_detection lane_detector.launch`

2020-09-08 02:39 UTC, kob51 commented on autovalet_lane_detection/README.md
> +This package contains our lane detection pipeline. The output of the lane detection will be used projected on the costmap, so that valid goals lying within the lane can be sent to the planner.
Adding now

2020-09-08 02:40 UTC, SubramanianKrish approved these changes, later dismissed

2020-09-08 02:57 UTC, evamo0508 approved these changes

2020-09-08 05:01 UTC, SubramanianKrish approved these changes

2020-09-08 05:02 UTC, merged